/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/account-api';
export * from './apis/agent-api';
export * from './apis/approval-setting-api';
export * from './apis/area-api';
export * from './apis/audit-log-api';
export * from './apis/azure-ad-custom-login-api';
export * from './apis/bank-infor-api';
export * from './apis/cancellation-condition-api';
export * from './apis/cancellation-type-api';
export * from './apis/commission-condition-api';
export * from './apis/commission-type-api';
export * from './apis/common-api';
export * from './apis/country-api';
export * from './apis/currency-api';
export * from './apis/customer-api';
export * from './apis/customer-address-api';
export * from './apis/customer-bank-account-api';
export * from './apis/customer-contact-person-api';
export * from './apis/customer-group-api';
export * from './apis/debt-report-api';
export * from './apis/department-api';
export * from './apis/discount-api';
export * from './apis/discount-line-api';
export * from './apis/employee-api';
export * from './apis/integration-api';
export * from './apis/location-api';
export * from './apis/notification-api';
export * from './apis/notification-time-setup-api';
export * from './apis/passenger-type-api';
export * from './apis/passenger-type-seat-api';
export * from './apis/payment-method-api';
export * from './apis/personal-api';
export * from './apis/position-api';
export * from './apis/product-api';
export * from './apis/product-category-api';
export * from './apis/product-group-api';
export * from './apis/product-type-api';
export * from './apis/quote-fit-api';
export * from './apis/quote-git-api';
export * from './apis/receivable-voucher-api';
export * from './apis/refund-voucher-api';
export * from './apis/region-api';
export * from './apis/resources-api';
export * from './apis/revenue-report-api';
export * from './apis/role-api';
export * from './apis/roles-api';
export * from './apis/route-api';
export * from './apis/sale-order-api';
export * from './apis/sale-order-line-api';
export * from './apis/sale-order-line-passenger-api';
export * from './apis/sale-order-line-traveller-api';
export * from './apis/tag-api';
export * from './apis/tour-api';
export * from './apis/tour-category-api';
export * from './apis/tour-fit-api';
export * from './apis/tour-git-api';
export * from './apis/tour-guide-api';
export * from './apis/tour-info-media-api';
export * from './apis/tour-infor-api';
export * from './apis/tour-schedule-fare-api';
export * from './apis/tour-schedule-media-api';
export * from './apis/tour-schedule-surcharge-api';
export * from './apis/tour-schedule-tour-guide-api';
export * from './apis/tour-service-api';
export * from './apis/tour-type-api';
export * from './apis/tour-visa-api';
export * from './apis/transportation-api';
export * from './apis/traveller-api';
export * from './apis/unit-of-measure-api';
export * from './apis/vat-api';
export * from './apis/vendor-api';
export * from './apis/vendor-address-api';
export * from './apis/vendor-bank-account-api';
export * from './apis/vendor-contact-person-api';
export * from './apis/vendor-group-api';
export * from './apis/voucher-parameter-api';

