/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ApprovalSettingDto } from '../models';
// @ts-ignore
import { ApprovalSettingGetUserForApproval200ResponseInner } from '../models';
// @ts-ignore
import { ErrorResult } from '../models';
// @ts-ignore
import { HttpValidationProblemDetails } from '../models';
// @ts-ignore
import { MyApprovalPermissionDto } from '../models';
// @ts-ignore
import { UpdateApprovalSettingRequest } from '../models';
/**
 * ApprovalSettingApi - axios parameter creator
 * @export
 */
export const ApprovalSettingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Approval Settings.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingGet: async (tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('approvalSettingGet', 'tenant', tenant)
            const localVarPath = `/api/v1/approvalsetting`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get My Approval Permissions.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingGetMyApprovalPermissions: async (tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('approvalSettingGetMyApprovalPermissions', 'tenant', tenant)
            const localVarPath = `/api/v1/approvalsetting/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Users For Approval Settings.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingGetUserForApproval: async (tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('approvalSettingGetUserForApproval', 'tenant', tenant)
            const localVarPath = `/api/v1/approvalsetting/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Approval Setting.
         * @param {string} tenant Description
         * @param {UpdateApprovalSettingRequest} updateApprovalSettingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingUpdate: async (tenant: string, updateApprovalSettingRequest: UpdateApprovalSettingRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('approvalSettingUpdate', 'tenant', tenant)
            // verify required parameter 'updateApprovalSettingRequest' is not null or undefined
            assertParamExists('approvalSettingUpdate', 'updateApprovalSettingRequest', updateApprovalSettingRequest)
            const localVarPath = `/api/v1/approvalsetting`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateApprovalSettingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApprovalSettingApi - functional programming interface
 * @export
 */
export const ApprovalSettingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApprovalSettingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Approval Settings.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approvalSettingGet(tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApprovalSettingDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approvalSettingGet(tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get My Approval Permissions.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approvalSettingGetMyApprovalPermissions(tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MyApprovalPermissionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approvalSettingGetMyApprovalPermissions(tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Users For Approval Settings.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approvalSettingGetUserForApproval(tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApprovalSettingGetUserForApproval200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approvalSettingGetUserForApproval(tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update Approval Setting.
         * @param {string} tenant Description
         * @param {UpdateApprovalSettingRequest} updateApprovalSettingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approvalSettingUpdate(tenant: string, updateApprovalSettingRequest: UpdateApprovalSettingRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approvalSettingUpdate(tenant, updateApprovalSettingRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ApprovalSettingApi - factory interface
 * @export
 */
export const ApprovalSettingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApprovalSettingApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Approval Settings.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingGet(tenant: string, options?: any): AxiosPromise<Array<ApprovalSettingDto>> {
            return localVarFp.approvalSettingGet(tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get My Approval Permissions.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingGetMyApprovalPermissions(tenant: string, options?: any): AxiosPromise<Array<MyApprovalPermissionDto>> {
            return localVarFp.approvalSettingGetMyApprovalPermissions(tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Users For Approval Settings.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingGetUserForApproval(tenant: string, options?: any): AxiosPromise<Array<ApprovalSettingGetUserForApproval200ResponseInner>> {
            return localVarFp.approvalSettingGetUserForApproval(tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Approval Setting.
         * @param {string} tenant Description
         * @param {UpdateApprovalSettingRequest} updateApprovalSettingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvalSettingUpdate(tenant: string, updateApprovalSettingRequest: UpdateApprovalSettingRequest, options?: any): AxiosPromise<Array<string>> {
            return localVarFp.approvalSettingUpdate(tenant, updateApprovalSettingRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApprovalSettingApi - object-oriented interface
 * @export
 * @class ApprovalSettingApi
 * @extends {BaseAPI}
 */
export class ApprovalSettingApi extends BaseAPI {
    /**
     * 
     * @summary Get Approval Settings.
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApprovalSettingApi
     */
    public approvalSettingGet(tenant: string, options?: AxiosRequestConfig) {
        return ApprovalSettingApiFp(this.configuration).approvalSettingGet(tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get My Approval Permissions.
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApprovalSettingApi
     */
    public approvalSettingGetMyApprovalPermissions(tenant: string, options?: AxiosRequestConfig) {
        return ApprovalSettingApiFp(this.configuration).approvalSettingGetMyApprovalPermissions(tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Users For Approval Settings.
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApprovalSettingApi
     */
    public approvalSettingGetUserForApproval(tenant: string, options?: AxiosRequestConfig) {
        return ApprovalSettingApiFp(this.configuration).approvalSettingGetUserForApproval(tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Approval Setting.
     * @param {string} tenant Description
     * @param {UpdateApprovalSettingRequest} updateApprovalSettingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApprovalSettingApi
     */
    public approvalSettingUpdate(tenant: string, updateApprovalSettingRequest: UpdateApprovalSettingRequest, options?: AxiosRequestConfig) {
        return ApprovalSettingApiFp(this.configuration).approvalSettingUpdate(tenant, updateApprovalSettingRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
