/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrorResult } from '../models';
// @ts-ignore
import { HttpValidationProblemDetails } from '../models';
// @ts-ignore
import { PaginationResponseOfAreaDto } from '../models';
// @ts-ignore
import { SearchAreasRequest } from '../models';
/**
 * AreaApi - axios parameter creator
 * @export
 */
export const AreaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Search areas using available filters.
         * @param {string} tenant Description
         * @param {SearchAreasRequest} searchAreasRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        areaSearch: async (tenant: string, searchAreasRequest: SearchAreasRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('areaSearch', 'tenant', tenant)
            // verify required parameter 'searchAreasRequest' is not null or undefined
            assertParamExists('areaSearch', 'searchAreasRequest', searchAreasRequest)
            const localVarPath = `/api/v1/area/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchAreasRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AreaApi - functional programming interface
 * @export
 */
export const AreaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AreaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Search areas using available filters.
         * @param {string} tenant Description
         * @param {SearchAreasRequest} searchAreasRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async areaSearch(tenant: string, searchAreasRequest: SearchAreasRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginationResponseOfAreaDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.areaSearch(tenant, searchAreasRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AreaApi - factory interface
 * @export
 */
export const AreaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AreaApiFp(configuration)
    return {
        /**
         * 
         * @summary Search areas using available filters.
         * @param {string} tenant Description
         * @param {SearchAreasRequest} searchAreasRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        areaSearch(tenant: string, searchAreasRequest: SearchAreasRequest, options?: any): AxiosPromise<PaginationResponseOfAreaDto> {
            return localVarFp.areaSearch(tenant, searchAreasRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AreaApi - object-oriented interface
 * @export
 * @class AreaApi
 * @extends {BaseAPI}
 */
export class AreaApi extends BaseAPI {
    /**
     * 
     * @summary Search areas using available filters.
     * @param {string} tenant Description
     * @param {SearchAreasRequest} searchAreasRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaApi
     */
    public areaSearch(tenant: string, searchAreasRequest: SearchAreasRequest, options?: AxiosRequestConfig) {
        return AreaApiFp(this.configuration).areaSearch(tenant, searchAreasRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
