/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrorResult } from '../models';
// @ts-ignore
import { HttpValidationProblemDetails } from '../models';
// @ts-ignore
import { NotificationTimeSetupDto } from '../models';
// @ts-ignore
import { UpdateNotificationTimeSetupRequest } from '../models';
/**
 * NotificationTimeSetupApi - axios parameter creator
 * @export
 */
export const NotificationTimeSetupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get notification setups.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationTimeSetupGet: async (tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('notificationTimeSetupGet', 'tenant', tenant)
            const localVarPath = `/api/v1/notificationtimesetup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update notification setups.
         * @param {string} tenant Description
         * @param {UpdateNotificationTimeSetupRequest} updateNotificationTimeSetupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationTimeSetupUpdate: async (tenant: string, updateNotificationTimeSetupRequest: UpdateNotificationTimeSetupRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('notificationTimeSetupUpdate', 'tenant', tenant)
            // verify required parameter 'updateNotificationTimeSetupRequest' is not null or undefined
            assertParamExists('notificationTimeSetupUpdate', 'updateNotificationTimeSetupRequest', updateNotificationTimeSetupRequest)
            const localVarPath = `/api/v1/notificationtimesetup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateNotificationTimeSetupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationTimeSetupApi - functional programming interface
 * @export
 */
export const NotificationTimeSetupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationTimeSetupApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get notification setups.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationTimeSetupGet(tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NotificationTimeSetupDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationTimeSetupGet(tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update notification setups.
         * @param {string} tenant Description
         * @param {UpdateNotificationTimeSetupRequest} updateNotificationTimeSetupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationTimeSetupUpdate(tenant: string, updateNotificationTimeSetupRequest: UpdateNotificationTimeSetupRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationTimeSetupUpdate(tenant, updateNotificationTimeSetupRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * NotificationTimeSetupApi - factory interface
 * @export
 */
export const NotificationTimeSetupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationTimeSetupApiFp(configuration)
    return {
        /**
         * 
         * @summary Get notification setups.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationTimeSetupGet(tenant: string, options?: any): AxiosPromise<Array<NotificationTimeSetupDto>> {
            return localVarFp.notificationTimeSetupGet(tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update notification setups.
         * @param {string} tenant Description
         * @param {UpdateNotificationTimeSetupRequest} updateNotificationTimeSetupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationTimeSetupUpdate(tenant: string, updateNotificationTimeSetupRequest: UpdateNotificationTimeSetupRequest, options?: any): AxiosPromise<void> {
            return localVarFp.notificationTimeSetupUpdate(tenant, updateNotificationTimeSetupRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationTimeSetupApi - object-oriented interface
 * @export
 * @class NotificationTimeSetupApi
 * @extends {BaseAPI}
 */
export class NotificationTimeSetupApi extends BaseAPI {
    /**
     * 
     * @summary Get notification setups.
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationTimeSetupApi
     */
    public notificationTimeSetupGet(tenant: string, options?: AxiosRequestConfig) {
        return NotificationTimeSetupApiFp(this.configuration).notificationTimeSetupGet(tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update notification setups.
     * @param {string} tenant Description
     * @param {UpdateNotificationTimeSetupRequest} updateNotificationTimeSetupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationTimeSetupApi
     */
    public notificationTimeSetupUpdate(tenant: string, updateNotificationTimeSetupRequest: UpdateNotificationTimeSetupRequest, options?: AxiosRequestConfig) {
        return NotificationTimeSetupApiFp(this.configuration).notificationTimeSetupUpdate(tenant, updateNotificationTimeSetupRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
