/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ConfirmQuoteRequest } from '../models';
// @ts-ignore
import { CreateQuoteRequest } from '../models';
// @ts-ignore
import { ErrorResult } from '../models';
// @ts-ignore
import { ExportQuoteRequest } from '../models';
// @ts-ignore
import { ExportQuotesRequest } from '../models';
// @ts-ignore
import { HttpValidationProblemDetails } from '../models';
// @ts-ignore
import { PaginationResponseOfSearchQuoteDto } from '../models';
// @ts-ignore
import { QuoteDetailDto } from '../models';
// @ts-ignore
import { SearchQuotesRequest } from '../models';
// @ts-ignore
import { UpdateQuoteRequest } from '../models';
/**
 * QuoteFitApi - axios parameter creator
 * @export
 */
export const QuoteFitApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} tenant Description
         * @param {ExportQuotesRequest} exportQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitAgencyExport: async (tenant: string, exportQuotesRequest: ExportQuotesRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitAgencyExport', 'tenant', tenant)
            // verify required parameter 'exportQuotesRequest' is not null or undefined
            assertParamExists('quoteFitAgencyExport', 'exportQuotesRequest', exportQuotesRequest)
            const localVarPath = `/api/v1/quotefit/agent/export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(exportQuotesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {ExportQuoteRequest} exportQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitAgencyExportDetail: async (id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quoteFitAgencyExportDetail', 'id', id)
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitAgencyExportDetail', 'tenant', tenant)
            // verify required parameter 'exportQuoteRequest' is not null or undefined
            assertParamExists('quoteFitAgencyExportDetail', 'exportQuoteRequest', exportQuoteRequest)
            const localVarPath = `/api/v1/quotefit/{id}/agent/export`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(exportQuoteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search Quote using available filters.
         * @param {string} tenant Description
         * @param {SearchQuotesRequest} searchQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitAgencySearch: async (tenant: string, searchQuotesRequest: SearchQuotesRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitAgencySearch', 'tenant', tenant)
            // verify required parameter 'searchQuotesRequest' is not null or undefined
            assertParamExists('quoteFitAgencySearch', 'searchQuotesRequest', searchQuotesRequest)
            const localVarPath = `/api/v1/quotefit/agent/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchQuotesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cancel Quote.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitCancel: async (id: string, tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quoteFitCancel', 'id', id)
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitCancel', 'tenant', tenant)
            const localVarPath = `/api/v1/quotefit/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} tenant Description
         * @param {ConfirmQuoteRequest} confirmQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitConfirm: async (tenant: string, confirmQuoteRequest: ConfirmQuoteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitConfirm', 'tenant', tenant)
            // verify required parameter 'confirmQuoteRequest' is not null or undefined
            assertParamExists('quoteFitConfirm', 'confirmQuoteRequest', confirmQuoteRequest)
            const localVarPath = `/api/v1/quotefit/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(confirmQuoteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new Quote.
         * @param {string} tenant Description
         * @param {CreateQuoteRequest} createQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitCreate: async (tenant: string, createQuoteRequest: CreateQuoteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitCreate', 'tenant', tenant)
            // verify required parameter 'createQuoteRequest' is not null or undefined
            assertParamExists('quoteFitCreate', 'createQuoteRequest', createQuoteRequest)
            const localVarPath = `/api/v1/quotefit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createQuoteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a Quote.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitDelete: async (id: string, tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quoteFitDelete', 'id', id)
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitDelete', 'tenant', tenant)
            const localVarPath = `/api/v1/quotefit/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} tenant Description
         * @param {ExportQuotesRequest} exportQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitExport: async (tenant: string, exportQuotesRequest: ExportQuotesRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitExport', 'tenant', tenant)
            // verify required parameter 'exportQuotesRequest' is not null or undefined
            assertParamExists('quoteFitExport', 'exportQuotesRequest', exportQuotesRequest)
            const localVarPath = `/api/v1/quotefit/export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(exportQuotesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {ExportQuoteRequest} exportQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitExportDetail: async (id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quoteFitExportDetail', 'id', id)
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitExportDetail', 'tenant', tenant)
            // verify required parameter 'exportQuoteRequest' is not null or undefined
            assertParamExists('quoteFitExportDetail', 'exportQuoteRequest', exportQuoteRequest)
            const localVarPath = `/api/v1/quotefit/{id}/export`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(exportQuoteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Quote detail.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitGet: async (id: string, tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quoteFitGet', 'id', id)
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitGet', 'tenant', tenant)
            const localVarPath = `/api/v1/quotefit/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Generate Quotes Code.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitGetCode: async (tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitGetCode', 'tenant', tenant)
            const localVarPath = `/api/v1/quotefit/gen-code`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search Quote using available filters.
         * @param {string} tenant Description
         * @param {SearchQuotesRequest} searchQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitSearch: async (tenant: string, searchQuotesRequest: SearchQuotesRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitSearch', 'tenant', tenant)
            // verify required parameter 'searchQuotesRequest' is not null or undefined
            assertParamExists('quoteFitSearch', 'searchQuotesRequest', searchQuotesRequest)
            const localVarPath = `/api/v1/quotefit/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchQuotesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitSendConfirm: async (id: string, tenant: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quoteFitSendConfirm', 'id', id)
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitSendConfirm', 'tenant', tenant)
            const localVarPath = `/api/v1/quotefit/{id}/send-confirm`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a new Quote.
         * @param {string} tenant Description
         * @param {UpdateQuoteRequest} updateQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitUpdate: async (tenant: string, updateQuoteRequest: UpdateQuoteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenant' is not null or undefined
            assertParamExists('quoteFitUpdate', 'tenant', tenant)
            // verify required parameter 'updateQuoteRequest' is not null or undefined
            assertParamExists('quoteFitUpdate', 'updateQuoteRequest', updateQuoteRequest)
            const localVarPath = `/api/v1/quotefit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

            if (tenant != null) {
                localVarHeaderParameter['tenant'] = String(tenant);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateQuoteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuoteFitApi - functional programming interface
 * @export
 */
export const QuoteFitApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuoteFitApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} tenant Description
         * @param {ExportQuotesRequest} exportQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitAgencyExport(tenant: string, exportQuotesRequest: ExportQuotesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitAgencyExport(tenant, exportQuotesRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {ExportQuoteRequest} exportQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitAgencyExportDetail(id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitAgencyExportDetail(id, tenant, exportQuoteRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Search Quote using available filters.
         * @param {string} tenant Description
         * @param {SearchQuotesRequest} searchQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitAgencySearch(tenant: string, searchQuotesRequest: SearchQuotesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginationResponseOfSearchQuoteDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitAgencySearch(tenant, searchQuotesRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Cancel Quote.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitCancel(id: string, tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitCancel(id, tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} tenant Description
         * @param {ConfirmQuoteRequest} confirmQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitConfirm(tenant: string, confirmQuoteRequest: ConfirmQuoteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitConfirm(tenant, confirmQuoteRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create a new Quote.
         * @param {string} tenant Description
         * @param {CreateQuoteRequest} createQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitCreate(tenant: string, createQuoteRequest: CreateQuoteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitCreate(tenant, createQuoteRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete a Quote.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitDelete(id: string, tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitDelete(id, tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} tenant Description
         * @param {ExportQuotesRequest} exportQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitExport(tenant: string, exportQuotesRequest: ExportQuotesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitExport(tenant, exportQuotesRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {ExportQuoteRequest} exportQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitExportDetail(id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitExportDetail(id, tenant, exportQuoteRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Quote detail.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitGet(id: string, tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteDetailDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitGet(id, tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Generate Quotes Code.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitGetCode(tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitGetCode(tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Search Quote using available filters.
         * @param {string} tenant Description
         * @param {SearchQuotesRequest} searchQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitSearch(tenant: string, searchQuotesRequest: SearchQuotesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginationResponseOfSearchQuoteDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitSearch(tenant, searchQuotesRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitSendConfirm(id: string, tenant: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitSendConfirm(id, tenant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update a new Quote.
         * @param {string} tenant Description
         * @param {UpdateQuoteRequest} updateQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteFitUpdate(tenant: string, updateQuoteRequest: UpdateQuoteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteFitUpdate(tenant, updateQuoteRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * QuoteFitApi - factory interface
 * @export
 */
export const QuoteFitApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuoteFitApiFp(configuration)
    return {
        /**
         * 
         * @param {string} tenant Description
         * @param {ExportQuotesRequest} exportQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitAgencyExport(tenant: string, exportQuotesRequest: ExportQuotesRequest, options?: any): AxiosPromise<File> {
            return localVarFp.quoteFitAgencyExport(tenant, exportQuotesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {ExportQuoteRequest} exportQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitAgencyExportDetail(id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options?: any): AxiosPromise<File> {
            return localVarFp.quoteFitAgencyExportDetail(id, tenant, exportQuoteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search Quote using available filters.
         * @param {string} tenant Description
         * @param {SearchQuotesRequest} searchQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitAgencySearch(tenant: string, searchQuotesRequest: SearchQuotesRequest, options?: any): AxiosPromise<PaginationResponseOfSearchQuoteDto> {
            return localVarFp.quoteFitAgencySearch(tenant, searchQuotesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cancel Quote.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitCancel(id: string, tenant: string, options?: any): AxiosPromise<string> {
            return localVarFp.quoteFitCancel(id, tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} tenant Description
         * @param {ConfirmQuoteRequest} confirmQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitConfirm(tenant: string, confirmQuoteRequest: ConfirmQuoteRequest, options?: any): AxiosPromise<string> {
            return localVarFp.quoteFitConfirm(tenant, confirmQuoteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new Quote.
         * @param {string} tenant Description
         * @param {CreateQuoteRequest} createQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitCreate(tenant: string, createQuoteRequest: CreateQuoteRequest, options?: any): AxiosPromise<string> {
            return localVarFp.quoteFitCreate(tenant, createQuoteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a Quote.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitDelete(id: string, tenant: string, options?: any): AxiosPromise<string> {
            return localVarFp.quoteFitDelete(id, tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} tenant Description
         * @param {ExportQuotesRequest} exportQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitExport(tenant: string, exportQuotesRequest: ExportQuotesRequest, options?: any): AxiosPromise<File> {
            return localVarFp.quoteFitExport(tenant, exportQuotesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {ExportQuoteRequest} exportQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitExportDetail(id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options?: any): AxiosPromise<File> {
            return localVarFp.quoteFitExportDetail(id, tenant, exportQuoteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Quote detail.
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitGet(id: string, tenant: string, options?: any): AxiosPromise<QuoteDetailDto> {
            return localVarFp.quoteFitGet(id, tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Generate Quotes Code.
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitGetCode(tenant: string, options?: any): AxiosPromise<string> {
            return localVarFp.quoteFitGetCode(tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search Quote using available filters.
         * @param {string} tenant Description
         * @param {SearchQuotesRequest} searchQuotesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitSearch(tenant: string, searchQuotesRequest: SearchQuotesRequest, options?: any): AxiosPromise<PaginationResponseOfSearchQuoteDto> {
            return localVarFp.quoteFitSearch(tenant, searchQuotesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {string} tenant Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitSendConfirm(id: string, tenant: string, options?: any): AxiosPromise<string> {
            return localVarFp.quoteFitSendConfirm(id, tenant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a new Quote.
         * @param {string} tenant Description
         * @param {UpdateQuoteRequest} updateQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteFitUpdate(tenant: string, updateQuoteRequest: UpdateQuoteRequest, options?: any): AxiosPromise<string> {
            return localVarFp.quoteFitUpdate(tenant, updateQuoteRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuoteFitApi - object-oriented interface
 * @export
 * @class QuoteFitApi
 * @extends {BaseAPI}
 */
export class QuoteFitApi extends BaseAPI {
    /**
     * 
     * @param {string} tenant Description
     * @param {ExportQuotesRequest} exportQuotesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitAgencyExport(tenant: string, exportQuotesRequest: ExportQuotesRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitAgencyExport(tenant, exportQuotesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {string} tenant Description
     * @param {ExportQuoteRequest} exportQuoteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitAgencyExportDetail(id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitAgencyExportDetail(id, tenant, exportQuoteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search Quote using available filters.
     * @param {string} tenant Description
     * @param {SearchQuotesRequest} searchQuotesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitAgencySearch(tenant: string, searchQuotesRequest: SearchQuotesRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitAgencySearch(tenant, searchQuotesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cancel Quote.
     * @param {string} id 
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitCancel(id: string, tenant: string, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitCancel(id, tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} tenant Description
     * @param {ConfirmQuoteRequest} confirmQuoteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitConfirm(tenant: string, confirmQuoteRequest: ConfirmQuoteRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitConfirm(tenant, confirmQuoteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new Quote.
     * @param {string} tenant Description
     * @param {CreateQuoteRequest} createQuoteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitCreate(tenant: string, createQuoteRequest: CreateQuoteRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitCreate(tenant, createQuoteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a Quote.
     * @param {string} id 
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitDelete(id: string, tenant: string, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitDelete(id, tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} tenant Description
     * @param {ExportQuotesRequest} exportQuotesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitExport(tenant: string, exportQuotesRequest: ExportQuotesRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitExport(tenant, exportQuotesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {string} tenant Description
     * @param {ExportQuoteRequest} exportQuoteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitExportDetail(id: string, tenant: string, exportQuoteRequest: ExportQuoteRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitExportDetail(id, tenant, exportQuoteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Quote detail.
     * @param {string} id 
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitGet(id: string, tenant: string, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitGet(id, tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Generate Quotes Code.
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitGetCode(tenant: string, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitGetCode(tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search Quote using available filters.
     * @param {string} tenant Description
     * @param {SearchQuotesRequest} searchQuotesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitSearch(tenant: string, searchQuotesRequest: SearchQuotesRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitSearch(tenant, searchQuotesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {string} tenant Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitSendConfirm(id: string, tenant: string, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitSendConfirm(id, tenant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a new Quote.
     * @param {string} tenant Description
     * @param {UpdateQuoteRequest} updateQuoteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteFitApi
     */
    public quoteFitUpdate(tenant: string, updateQuoteRequest: UpdateQuoteRequest, options?: AxiosRequestConfig) {
        return QuoteFitApiFp(this.configuration).quoteFitUpdate(tenant, updateQuoteRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
