const QueryKeys = {
    GET_TOUR_SCHEDULE_FARE_INFOS: 'GET_TOUR_SCHEDULE_FARE_INFOS',
    GET_DISCOUNTS: 'GET_DISCOUNTS',
    GET_ESTIMATE_DISCOUNTS: 'GET_ESTIMATE_DISCOUNTS',
};

export default QueryKeys;
