/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApplicationRequest
 */
export interface ApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    'information'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    'logo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    'publicUrl'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRequest
     */
    'enable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    'clientId'?: string;
}

