/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserGroupAssignment } from './user-group-assignment';

/**
 * 
 * @export
 * @interface AssignUsersGroupRequest
 */
export interface AssignUsersGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof AssignUsersGroupRequest
     */
    'groupId'?: string;
    /**
     * 
     * @type {Array<UserGroupAssignment>}
     * @memberof AssignUsersGroupRequest
     */
    'users'?: Array<UserGroupAssignment>;
}

