/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RoleGroupAssignment } from './role-group-assignment';

/**
 * 
 * @export
 * @interface AssignRolesGroupRequest
 */
export interface AssignRolesGroupRequest {
    /**
     * 
     * @type {Array<RoleGroupAssignment>}
     * @memberof AssignRolesGroupRequest
     */
    'roles'?: Array<RoleGroupAssignment>;
    /**
     * 
     * @type {boolean}
     * @memberof AssignRolesGroupRequest
     */
    'isDefault'?: boolean | null;
}

