/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonGroupDtoAllOf
 */
export interface CommonGroupDtoAllOf {
    /**
     * 
     * @type {string}
     * @memberof CommonGroupDtoAllOf
     */
    'systemId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonGroupDtoAllOf
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonGroupDtoAllOf
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonGroupDtoAllOf
     */
    'representative'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonGroupDtoAllOf
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonGroupDtoAllOf
     */
    'accountCreation'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CommonGroupDtoAllOf
     */
    'inUse'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CommonGroupDtoAllOf
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CommonGroupDtoAllOf
     */
    'createdOn'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CommonGroupDtoAllOf
     */
    'roleId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonGroupDtoAllOf
     */
    'source'?: string | null;
}

