/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentDto } from './document-dto';
// May contain unused imports in some cases
// @ts-ignore
import { GroupInfoBankDto } from './group-info-bank-dto';
// May contain unused imports in some cases
// @ts-ignore
import { GroupInfoDtoAddress } from './group-info-dto-address';

/**
 * 
 * @export
 * @interface GroupInfoDto
 */
export interface GroupInfoDto {
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'shortName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'taxCode'?: string | null;
    /**
     * 
     * @type {GroupInfoDtoAddress}
     * @memberof GroupInfoDto
     */
    'address'?: GroupInfoDtoAddress | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'hotline'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'messengerDeepLink'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'website'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'groupId'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GroupInfoDto
     */
    'effectiveDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GroupInfoDto
     */
    'expirationDate'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'representative'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'businessType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupInfoDto
     */
    'personInChargeId'?: string | null;
    /**
     * 
     * @type {Array<GroupInfoBankDto>}
     * @memberof GroupInfoDto
     */
    'bankInfos'?: Array<GroupInfoBankDto>;
    /**
     * 
     * @type {Array<DocumentDto>}
     * @memberof GroupInfoDto
     */
    'documents'?: Array<DocumentDto>;
}

