/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClientDtoGroup } from './client-dto-group';
// May contain unused imports in some cases
// @ts-ignore
import { GroupDtoGroupInfo } from './group-dto-group-info';
// May contain unused imports in some cases
// @ts-ignore
import { GroupPositionDto } from './group-position-dto';
// May contain unused imports in some cases
// @ts-ignore
import { RoleDto } from './role-dto';
// May contain unused imports in some cases
// @ts-ignore
import { UserDetailsDto } from './user-details-dto';

/**
 * 
 * @export
 * @interface GroupDto
 */
export interface GroupDto {
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'systemId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'normalizedName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GroupDto
     */
    'isGlobal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'logo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'salesStaffId'?: string | null;
    /**
     * 
     * @type {Array<UserDetailsDto>}
     * @memberof GroupDto
     */
    'salesStaff'?: Array<UserDetailsDto> | null;
    /**
     * 
     * @type {Array<UserDetailsDto>}
     * @memberof GroupDto
     */
    'manager'?: Array<UserDetailsDto> | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'managerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'hotline'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'messengerDeepLink'?: string | null;
    /**
     * 
     * @type {GroupDtoGroupInfo}
     * @memberof GroupDto
     */
    'groupInfo'?: GroupDtoGroupInfo | null;
    /**
     * 
     * @type {Array<RoleDto>}
     * @memberof GroupDto
     */
    'roles'?: Array<RoleDto>;
    /**
     * 
     * @type {Array<GroupDto>}
     * @memberof GroupDto
     */
    'subGroups'?: Array<GroupDto>;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'parentId'?: string | null;
    /**
     * 
     * @type {ClientDtoGroup}
     * @memberof GroupDto
     */
    'parent'?: ClientDtoGroup | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'source'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GroupDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Array<GroupPositionDto>}
     * @memberof GroupDto
     */
    'groupPositions'?: Array<GroupPositionDto>;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'agentState'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'branchState'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GroupDto
     */
    'inUse'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    'branchId'?: string | null;
}

