/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ViewUserGroupWithPrivilegeDto } from './view-user-group-with-privilege-dto';

/**
 * 
 * @export
 * @interface PaginationResponseOfViewUserGroupWithPrivilegeDto
 */
export interface PaginationResponseOfViewUserGroupWithPrivilegeDto {
    /**
     * 
     * @type {Array<ViewUserGroupWithPrivilegeDto>}
     * @memberof PaginationResponseOfViewUserGroupWithPrivilegeDto
     */
    'data'?: Array<ViewUserGroupWithPrivilegeDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfViewUserGroupWithPrivilegeDto
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfViewUserGroupWithPrivilegeDto
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfViewUserGroupWithPrivilegeDto
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfViewUserGroupWithPrivilegeDto
     */
    'pageSize'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfViewUserGroupWithPrivilegeDto
     */
    'hasPreviousPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfViewUserGroupWithPrivilegeDto
     */
    'hasNextPage'?: boolean;
}

