/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncLocalAccountStandaloneRequest
 */
export interface SyncLocalAccountStandaloneRequest {
    /**
     * 
     * @type {string}
     * @memberof SyncLocalAccountStandaloneRequest
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncLocalAccountStandaloneRequest
     */
    'groupId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SyncLocalAccountStandaloneRequest
     */
    'mustResetPassword'?: boolean;
}

