/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TenantDto
 */
export interface TenantDto {
    /**
     * 
     * @type {string}
     * @memberof TenantDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantDto
     */
    'connectionString'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantDto
     */
    'adminEmail'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TenantDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TenantDto
     */
    'validUpto'?: Date;
    /**
     * 
     * @type {string}
     * @memberof TenantDto
     */
    'issuer'?: string | null;
}

