/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TourOpsCreateGroupRequestOfAgentDto
 */
export interface TourOpsCreateGroupRequestOfAgentDto {
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'shortName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'representative'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'taxCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'bankAccount'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'bankName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'website'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'parentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'logo'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'isActive'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourOpsCreateGroupRequestOfAgentDto
     */
    'name'?: string;
}

