/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TourOpsCreateGroupRequestOfBranchDto } from './tour-ops-create-group-request-of-branch-dto';

/**
 * @type UpdateBranchRequest
 * @export
 */
export type UpdateBranchRequest = TourOpsCreateGroupRequestOfBranchDto;


