/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA Identity Next
 * TripOTA Identity Next built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ViewUserHasPermissions
 */
export interface ViewUserHasPermissions {
    /**
     * 
     * @type {string}
     * @memberof ViewUserHasPermissions
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewUserHasPermissions
     */
    'objectId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewUserHasPermissions
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewUserHasPermissions
     */
    'claimValue'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewUserHasPermissions
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewUserHasPermissions
     */
    'lastName'?: string | null;
}

