# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - releases/*

resources:
 repositories:
   - repository: deployment-repo
     type: git
     name: TripOTAFramework/TripOTA.Deployment
     ref: release
     persistCredentials: true
  

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'fef8b8a4-7c23-411f-9aed-b70ca8a16c13'
  imageRepository: 'tour-operation-react'
  imageRepositoryUAT: 'tour-operation-react-uat'
  deploymentDirectory: 'tour-operation-react/dev'
  containerRegistry: 'hnhprodacr.azurecr.io'
  containerName: 'tour-operation-react'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  dockerfilePathUAT: '$(Build.SourcesDirectory)/Dockerfile.uat'
  tag: '$(Build.SourceBranchName)-$(Build.BuildId)'
  componentName: 'Tour Operation react'

pool:
  name: "Default"

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self
      lfs: true
      submodules: recursive
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build and push an image to container registry env uat
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryUAT)
        dockerfile: $(dockerfilePathUAT)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)