/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccommodationFilterDtoOfInteger
 */
export interface AccommodationFilterDtoOfInteger {
    /**
     * 
     * @type {number}
     * @memberof AccommodationFilterDtoOfInteger
     */
    'value'?: number;
    /**
     * 
     * @type {string}
     * @memberof AccommodationFilterDtoOfInteger
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof AccommodationFilterDtoOfInteger
     */
    'count'?: number | null;
}

