/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddTripFlightByTravelerCommandAllOf } from './add-trip-flight-by-traveler-command-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { AddTripFlightByTravelerCommandAllOfFlightType } from './add-trip-flight-by-traveler-command-all-of-flight-type';
// May contain unused imports in some cases
// @ts-ignore
import { FareRequestDto } from './fare-request-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PassengerInfo } from './passenger-info';
// May contain unused imports in some cases
// @ts-ignore
import { TripContactDto } from './trip-contact-dto';
// May contain unused imports in some cases
// @ts-ignore
import { TripRequestBaseDto } from './trip-request-base-dto';

/**
 * @type AddTripFlightByTravelerCommand
 * @export
 */
export type AddTripFlightByTravelerCommand = AddTripFlightByTravelerCommandAllOf & TripRequestBaseDto;


