/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AirportDtoCity } from './airport-dto-city';
// May contain unused imports in some cases
// @ts-ignore
import { TranslationDto } from './translation-dto';

/**
 * Area
 * @export
 * @interface AreaDto
 */
export interface AreaDto {
    /**
     * 
     * @type {string}
     * @memberof AreaDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AreaDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {Array<TranslationDto>}
     * @memberof AreaDto
     */
    'translatedNames'?: Array<TranslationDto>;
    /**
     * 
     * @type {number}
     * @memberof AreaDto
     */
    'longitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof AreaDto
     */
    'latitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof AreaDto
     */
    'cityId'?: string;
    /**
     * 
     * @type {AirportDtoCity}
     * @memberof AreaDto
     */
    'city'?: AirportDtoCity | null;
}

