/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AirportDtoProvince } from './airport-dto-province';
// May contain unused imports in some cases
// @ts-ignore
import { TranslationDto } from './translation-dto';

/**
 * City
 * @export
 * @interface CityDto
 */
export interface CityDto {
    /**
     * 
     * @type {string}
     * @memberof CityDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CityDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CityDto
     */
    'code'?: string;
    /**
     * 
     * @type {number}
     * @memberof CityDto
     */
    'longitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof CityDto
     */
    'latitude'?: number;
    /**
     * 
     * @type {Array<TranslationDto>}
     * @memberof CityDto
     */
    'translatedNames'?: Array<TranslationDto>;
    /**
     * 
     * @type {AirportDtoProvince}
     * @memberof CityDto
     */
    'province'?: AirportDtoProvince | null;
}

