/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactDto2
 */
export interface ContactDto2 {
    /**
     * 
     * @type {string}
     * @memberof ContactDto2
     */
    'fullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDto2
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDto2
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDto2
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDto2
     */
    'position'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDto2
     */
    'contactType'?: string;
}

