/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeDetailDtoAllOf
 */
export interface EmployeeDetailDtoAllOf {
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailDtoAllOf
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailDtoAllOf
     */
    'objectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailDtoAllOf
     */
    'passportNumber'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeDetailDtoAllOf
     */
    'passportIssueDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeDetailDtoAllOf
     */
    'passportExpiration'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailDtoAllOf
     */
    'nationality'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailDtoAllOf
     */
    'memberCardAirline'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailDtoAllOf
     */
    'memberCardRank'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailDtoAllOf
     */
    'memberCardNumber'?: string | null;
}

