/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeBaseDto
 */
export interface EmployeeBaseDto {
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'objectId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'employeeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeBaseDto
     */
    'birthday'?: Date;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'areaCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'imageUrl'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeBaseDto
     */
    'gender'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeBaseDto
     */
    'emailConfirmed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeBaseDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmployeeBaseDto
     */
    'fullName'?: string;
}

