/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FareDataInfoDto } from './fare-data-info-dto';

/**
 * 
 * @export
 * @interface FlightServicesRequest
 */
export interface FlightServicesRequest {
    /**
     * 
     * @type {string}
     * @memberof FlightServicesRequest
     */
    'startPoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof FlightServicesRequest
     */
    'endPoint'?: string;
    /**
     * 
     * @type {Array<FareDataInfoDto>}
     * @memberof FlightServicesRequest
     */
    'listFareData'?: Array<FareDataInfoDto> | null;
}

