/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HotelGuestDto
 */
export interface HotelGuestDto {
    /**
     * 
     * @type {string}
     * @memberof HotelGuestDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof HotelGuestDto
     */
    'firstMiddleName': string;
    /**
     * 
     * @type {string}
     * @memberof HotelGuestDto
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof HotelGuestDto
     */
    'area'?: string;
    /**
     * 
     * @type {string}
     * @memberof HotelGuestDto
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof HotelGuestDto
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof HotelGuestDto
     */
    'nationality'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof HotelGuestDto
     */
    'gender'?: boolean;
}

