/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MembershipDto
 */
export interface MembershipDto {
    /**
     * 
     * @type {string}
     * @memberof MembershipDto
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipDto
     */
    'airline'?: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipDto
     */
    'rank'?: string;
}

