/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NotificationType } from './notification-type';

/**
 * 
 * @export
 * @interface NotificationMessageBase
 */
export interface NotificationMessageBase {
    /**
     * 
     * @type {string}
     * @memberof NotificationMessageBase
     */
    'title'?: string;
    /**
     * 
     * @type {NotificationType}
     * @memberof NotificationMessageBase
     */
    'type'?: NotificationType;
    /**
     * 
     * @type {string}
     * @memberof NotificationMessageBase
     */
    'userId'?: string;
    /**
     * 
     * @type {any}
     * @memberof NotificationMessageBase
     */
    'data'?: any | null;
}



