/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TripSyntheticDto } from './trip-synthetic-dto';

/**
 * 
 * @export
 * @interface PaginationResponseOfTripSyntheticDto
 */
export interface PaginationResponseOfTripSyntheticDto {
    /**
     * 
     * @type {Array<TripSyntheticDto>}
     * @memberof PaginationResponseOfTripSyntheticDto
     */
    'data'?: Array<TripSyntheticDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfTripSyntheticDto
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfTripSyntheticDto
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfTripSyntheticDto
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfTripSyntheticDto
     */
    'pageSize'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfTripSyntheticDto
     */
    'hasPreviousPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfTripSyntheticDto
     */
    'hasNextPage'?: boolean;
}

