/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FilterOption } from './filter-option';
// May contain unused imports in some cases
// @ts-ignore
import { NotificationMessageDto } from './notification-message-dto';

/**
 * 
 * @export
 * @interface PaginationResponseOfNotificationMessageDto
 */
export interface PaginationResponseOfNotificationMessageDto {
    /**
     * 
     * @type {Array<NotificationMessageDto>}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'data'?: Array<NotificationMessageDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'pageSize'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'hasPreviousPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'hasNextPage'?: boolean;
    /**
     * 
     * @type {Array<FilterOption>}
     * @memberof PaginationResponseOfNotificationMessageDto
     */
    'filterOptions'?: Array<FilterOption> | null;
}

