/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SearchFlightMonthRequest
 */
export interface SearchFlightMonthRequest {
    /**
     * 
     * @type {string}
     * @memberof SearchFlightMonthRequest
     */
    'startPoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchFlightMonthRequest
     */
    'endPoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchFlightMonthRequest
     */
    'airline'?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchFlightMonthRequest
     */
    'month'?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchFlightMonthRequest
     */
    'year'?: number;
}

