/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SearchHotelsRequestAccommodationFilter } from './search-hotels-request-accommodation-filter';
// May contain unused imports in some cases
// @ts-ignore
import { SortBy } from './sort-by';

/**
 * 
 * @export
 * @interface SearchHotelsRequest
 */
export interface SearchHotelsRequest {
    /**
     * 
     * @type {number}
     * @memberof SearchHotelsRequest
     */
    'waitTime'?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof SearchHotelsRequest
     */
    'checkIn'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SearchHotelsRequest
     */
    'checkOut'?: Date;
    /**
     * 
     * @type {number}
     * @memberof SearchHotelsRequest
     */
    'rooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchHotelsRequest
     */
    'adults'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof SearchHotelsRequest
     */
    'childrenAges'?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof SearchHotelsRequest
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchHotelsRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchHotelsRequest
     */
    'selectedGeographicalEntityId'?: string;
    /**
     * 
     * @type {SearchHotelsRequestAccommodationFilter}
     * @memberof SearchHotelsRequest
     */
    'accommodationFilter'?: SearchHotelsRequestAccommodationFilter | null;
    /**
     * 
     * @type {boolean}
     * @memberof SearchHotelsRequest
     */
    'needReturnFilters'?: boolean;
    /**
     * 
     * @type {Array<SortBy>}
     * @memberof SearchHotelsRequest
     */
    'sorts'?: Array<SortBy> | null;
}

