/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Cabin } from './cabin';

/**
 * 
 * @export
 * @interface SeatMap
 */
export interface SeatMap {
    /**
     * 
     * @type {string}
     * @memberof SeatMap
     */
    'startPoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatMap
     */
    'endPoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatMap
     */
    'flightNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatMap
     */
    'equipment'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatMap
     */
    'operating'?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatMap
     */
    'marketing'?: string;
    /**
     * 
     * @type {Date}
     * @memberof SeatMap
     */
    'departDate'?: Date;
    /**
     * 
     * @type {Array<Cabin>}
     * @memberof SeatMap
     */
    'listCabin'?: Array<Cabin>;
}

