/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SourceProviderIntegrationDtoProvider } from './source-provider-integration-dto-provider';
// May contain unused imports in some cases
// @ts-ignore
import { SourceProviderIntegrationDtoType } from './source-provider-integration-dto-type';

/**
 * 
 * @export
 * @interface SourceProviderIntegrationDto
 */
export interface SourceProviderIntegrationDto {
    /**
     * 
     * @type {SourceProviderIntegrationDtoType}
     * @memberof SourceProviderIntegrationDto
     */
    'type'?: SourceProviderIntegrationDtoType;
    /**
     * Key value corresponding to \"Id\" in master-data tables.
     * @type {string}
     * @memberof SourceProviderIntegrationDto
     */
    'masterDataId'?: string;
    /**
     * Key value corresponding to \"Id\" in third party data.
     * @type {string}
     * @memberof SourceProviderIntegrationDto
     */
    'providerId'?: string;
    /**
     * 
     * @type {SourceProviderIntegrationDtoProvider}
     * @memberof SourceProviderIntegrationDto
     */
    'provider'?: SourceProviderIntegrationDtoProvider;
}

