/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EmployeeBaseDto } from './employee-base-dto';

/**
 * 
 * @export
 * @interface TitleLevelDto
 */
export interface TitleLevelDto {
    /**
     * 
     * @type {string}
     * @memberof TitleLevelDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TitleLevelDto
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TitleLevelDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Array<EmployeeBaseDto>}
     * @memberof TitleLevelDto
     */
    'employees'?: Array<EmployeeBaseDto>;
}

