/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApproverSettingDto } from './approver-setting-dto';
// May contain unused imports in some cases
// @ts-ignore
import { FlightPolicyDto } from './flight-policy-dto';
// May contain unused imports in some cases
// @ts-ignore
import { HotelPolicyDto } from './hotel-policy-dto';

/**
 * 
 * @export
 * @interface TravelerBudgetPolicyDto
 */
export interface TravelerBudgetPolicyDto {
    /**
     * 
     * @type {FlightPolicyDto}
     * @memberof TravelerBudgetPolicyDto
     */
    'flightPolicy'?: FlightPolicyDto;
    /**
     * 
     * @type {HotelPolicyDto}
     * @memberof TravelerBudgetPolicyDto
     */
    'hotelPolicy'?: HotelPolicyDto;
    /**
     * 
     * @type {Array<ApproverSettingDto>}
     * @memberof TravelerBudgetPolicyDto
     */
    'approvalProcesses'?: Array<ApproverSettingDto>;
}

