/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActionType } from './action-type';
// May contain unused imports in some cases
// @ts-ignore
import { FieldChangeDto } from './field-change-dto';
// May contain unused imports in some cases
// @ts-ignore
import { TravelPolicyHistoryDtoNewValue } from './travel-policy-history-dto-new-value';

/**
 * 
 * @export
 * @interface TravelPolicyHistoryDto
 */
export interface TravelPolicyHistoryDto {
    /**
     * 
     * @type {string}
     * @memberof TravelPolicyHistoryDto
     */
    'travelPolicyId'?: string;
    /**
     * 
     * @type {ActionType}
     * @memberof TravelPolicyHistoryDto
     */
    'action'?: ActionType;
    /**
     * 
     * @type {TravelPolicyHistoryDtoNewValue}
     * @memberof TravelPolicyHistoryDto
     */
    'newValue'?: TravelPolicyHistoryDtoNewValue | null;
    /**
     * 
     * @type {TravelPolicyHistoryDtoNewValue}
     * @memberof TravelPolicyHistoryDto
     */
    'oldValue'?: TravelPolicyHistoryDtoNewValue | null;
    /**
     * 
     * @type {Array<FieldChangeDto>}
     * @memberof TravelPolicyHistoryDto
     */
    'changes'?: Array<FieldChangeDto>;
    /**
     * 
     * @type {string}
     * @memberof TravelPolicyHistoryDto
     */
    'lastModifiedByName'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TravelPolicyHistoryDto
     */
    'lastModifiedOn'?: Date;
    /**
     * 
     * @type {string}
     * @memberof TravelPolicyHistoryDto
     */
    'version'?: string;
}



