/* tslint:disable */
/* eslint-disable */
/**
 * TripOTA TMC WebAPI
 * The TripOTA TMC WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: touch@tripota.com.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SaveContactInfoCommand } from './save-contact-info-command';
// May contain unused imports in some cases
// @ts-ignore
import { TripInfoDtoAllOfAdditionInfo } from './trip-info-dto-all-of-addition-info';
// May contain unused imports in some cases
// @ts-ignore
import { TripPlanStatus } from './trip-plan-status';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateTripFlightInfoCommand } from './update-trip-flight-info-command';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateTripHotelInfoCommand } from './update-trip-hotel-info-command';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateTripInfoByBookerCommandAllOf } from './update-trip-info-by-booker-command-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateTripInfoByTravelerCommand } from './update-trip-info-by-traveler-command';

/**
 * @type UpdateTripInfoByBookerCommand
 * @export
 */
export type UpdateTripInfoByBookerCommand = UpdateTripInfoByBookerCommandAllOf & UpdateTripInfoByTravelerCommand;


