/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActiveStatus } from './active-status';

/**
 * 
 * @export
 * @interface AccountDto
 */
export interface AccountDto {
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'roleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'roleNameAlias'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'branchName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'branchId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'groupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'groupId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccountDto
     */
    'isFullAccess'?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AccountDto
     */
    'createdOn'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'fullName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'source'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'departmentName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'positionName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'imageUrl'?: string | null;
    /**
     * 
     * @type {ActiveStatus}
     * @memberof AccountDto
     */
    'status'?: ActiveStatus;
}



