/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApproverDto } from './approver-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ApproverType } from './approver-type';

/**
 * 
 * @export
 * @interface ApprovalSettingDto
 */
export interface ApprovalSettingDto {
    /**
     * 
     * @type {string}
     * @memberof ApprovalSettingDto
     */
    'id'?: string;
    /**
     * 
     * @type {ApproverType}
     * @memberof ApprovalSettingDto
     */
    'approverType'?: ApproverType;
    /**
     * 
     * @type {string}
     * @memberof ApprovalSettingDto
     */
    'approverName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApprovalSettingDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Array<ApproverDto>}
     * @memberof ApprovalSettingDto
     */
    'approvers'?: Array<ApproverDto>;
}



