/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApprovalDto } from './approval-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ApproverType2 } from './approver-type2';
// May contain unused imports in some cases
// @ts-ignore
import { UserForApprovalDto } from './user-for-approval-dto';

/**
 * @type ApprovalSettingGetUserForApproval200ResponseInner
 * @export
 */
export type ApprovalSettingGetUserForApproval200ResponseInner = ApprovalDto;


