/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ObjectType } from './object-type';

/**
 * 
 * @export
 * @interface CommissionConditionDtoAllOf
 */
export interface CommissionConditionDtoAllOf {
    /**
     * 
     * @type {string}
     * @memberof CommissionConditionDtoAllOf
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommissionConditionDtoAllOf
     */
    'tourScheduleId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommissionConditionDtoAllOf
     */
    'commissionTypeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommissionConditionDtoAllOf
     */
    'commissionTypeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommissionConditionDtoAllOf
     */
    'passengerTypeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommissionConditionDtoAllOf
     */
    'passengerTypeName'?: string;
    /**
     * 
     * @type {ObjectType}
     * @memberof CommissionConditionDtoAllOf
     */
    'commissionTypeObjectType'?: ObjectType;
}



