/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SaleOrderLineRequest } from './sale-order-line-request';
// May contain unused imports in some cases
// @ts-ignore
import { SaleOrderLineTravellerRequest } from './sale-order-line-traveller-request';

/**
 * 
 * @export
 * @interface CreateSaleOrderRequestAllOf
 */
export interface CreateSaleOrderRequestAllOf {
    /**
     * 
     * @type {boolean}
     * @memberof CreateSaleOrderRequestAllOf
     */
    'isOverloadConfirmed'?: boolean;
    /**
     * 
     * @type {Array<SaleOrderLineTravellerRequest>}
     * @memberof CreateSaleOrderRequestAllOf
     */
    'travellers'?: Array<SaleOrderLineTravellerRequest>;
    /**
     * 
     * @type {Array<SaleOrderLineRequest>}
     * @memberof CreateSaleOrderRequestAllOf
     */
    'saleOrderLines'?: Array<SaleOrderLineRequest>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSaleOrderRequestAllOf
     */
    'isTransfer'?: boolean;
}

