/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateCurrencyRequest
 */
export interface CreateCurrencyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCurrencyRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateCurrencyRequest
     */
    'currencyCode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRequest
     */
    'rate'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCurrencyRequest
     */
    'displayLocale'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCurrencyRequest
     */
    'customFormatting'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRequest
     */
    'displayOrder'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRequest
     */
    'roundOrderItemsEnabled'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRequest
     */
    'roundNumDecimals'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRequest
     */
    'roundOrderTotalEnabled'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRequest
     */
    'roundOrderTotalDenominator'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRequest
     */
    'roundOrderTotalRule'?: number | null;
}

