/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DiscountConditionType } from './discount-condition-type';
// May contain unused imports in some cases
// @ts-ignore
import { DiscountLineRequest } from './discount-line-request';
// May contain unused imports in some cases
// @ts-ignore
import { DiscountType } from './discount-type';

/**
 * @type DiscountLineDto
 * @export
 */
export type DiscountLineDto = DiscountLineRequest;


