/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DiscountConditionType } from './discount-condition-type';
// May contain unused imports in some cases
// @ts-ignore
import { DiscountOnType } from './discount-on-type';
// May contain unused imports in some cases
// @ts-ignore
import { DiscountType } from './discount-type';

/**
 * 
 * @export
 * @interface DiscountDto
 */
export interface DiscountDto {
    /**
     * 
     * @type {string}
     * @memberof DiscountDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DiscountDto
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof DiscountDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DiscountDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DiscountDto
     */
    'currencyId'?: string;
    /**
     * 
     * @type {Date}
     * @memberof DiscountDto
     */
    'startDate'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DiscountDto
     */
    'endDate'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DiscountDto
     */
    'createdOn'?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof DiscountDto
     */
    'isUsed'?: boolean;
    /**
     * 
     * @type {DiscountOnType}
     * @memberof DiscountDto
     */
    'type'?: DiscountOnType;
    /**
     * 
     * @type {number}
     * @memberof DiscountDto
     */
    'remainingQuantity'?: number;
    /**
     * 
     * @type {DiscountType}
     * @memberof DiscountDto
     */
    'discountType'?: DiscountType;
    /**
     * 
     * @type {number}
     * @memberof DiscountDto
     */
    'value'?: number;
    /**
     * 
     * @type {number}
     * @memberof DiscountDto
     */
    'quantity'?: number;
    /**
     * 
     * @type {DiscountConditionType}
     * @memberof DiscountDto
     */
    'discountConditionType'?: DiscountConditionType;
}



