/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleStatus } from './tour-schedule-status';

/**
 * 
 * @export
 * @interface ExportTourScheduleRequestAllOf
 */
export interface ExportTourScheduleRequestAllOf {
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'tourCategoryId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'departureLocationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'destinationLocationId'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'departureDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'endDate'?: Date | null;
    /**
     * 
     * @type {Array<TourScheduleStatus>}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'status'?: Array<TourScheduleStatus>;
    /**
     * 
     * @type {Date}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'fromDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'toDate'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'hasUnpaidSaleOrders'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'connectionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'locale'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'fileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'routeId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExportTourScheduleRequestAllOf
     */
    'typeCode'?: string | null;
}

