/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BaseFilterAdvancedFilter } from './base-filter-advanced-filter';
// May contain unused imports in some cases
// @ts-ignore
import { BaseFilterAdvancedSearch } from './base-filter-advanced-search';
// May contain unused imports in some cases
// @ts-ignore
import { ExportReceivableVoucherRequestAllOf } from './export-receivable-voucher-request-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { PaginationFilter } from './pagination-filter';
// May contain unused imports in some cases
// @ts-ignore
import { ReceivableType2 } from './receivable-type2';
// May contain unused imports in some cases
// @ts-ignore
import { SearchReceivableVouchersRequestAllOfReceivableType } from './search-receivable-vouchers-request-all-of-receivable-type';
// May contain unused imports in some cases
// @ts-ignore
import { VoucherStatus } from './voucher-status';

/**
 * @type ExportReceivableVoucherRequest
 * @export
 */
export type ExportReceivableVoucherRequest = ExportReceivableVoucherRequestAllOf & PaginationFilter;


