/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SaleOrderByDiscountIdDtoStatus } from './sale-order-by-discount-id-dto-status';

/**
 * 
 * @export
 * @interface GetSaleOrderTotalBySearchRequest
 */
export interface GetSaleOrderTotalBySearchRequest {
    /**
     * 
     * @type {string}
     * @memberof GetSaleOrderTotalBySearchRequest
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSaleOrderTotalBySearchRequest
     */
    'tourScheduleId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSaleOrderTotalBySearchRequest
     */
    'currencyId'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetSaleOrderTotalBySearchRequest
     */
    'fromDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GetSaleOrderTotalBySearchRequest
     */
    'toDate'?: Date | null;
    /**
     * 
     * @type {SaleOrderByDiscountIdDtoStatus}
     * @memberof GetSaleOrderTotalBySearchRequest
     */
    'status'?: SaleOrderByDiscountIdDtoStatus | null;
    /**
     * 
     * @type {string}
     * @memberof GetSaleOrderTotalBySearchRequest
     */
    'orderNo'?: string;
}

