/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ReceivableVoucherSearchDto } from './receivable-voucher-search-dto';

/**
 * 
 * @export
 * @interface PaginationResponseOfReceivableVoucherSearchDto
 */
export interface PaginationResponseOfReceivableVoucherSearchDto {
    /**
     * 
     * @type {Array<ReceivableVoucherSearchDto>}
     * @memberof PaginationResponseOfReceivableVoucherSearchDto
     */
    'data'?: Array<ReceivableVoucherSearchDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfReceivableVoucherSearchDto
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfReceivableVoucherSearchDto
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfReceivableVoucherSearchDto
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationResponseOfReceivableVoucherSearchDto
     */
    'pageSize'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfReceivableVoucherSearchDto
     */
    'hasPreviousPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResponseOfReceivableVoucherSearchDto
     */
    'hasNextPage'?: boolean;
}

