/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductTypeDto
 */
export interface ProductTypeDto {
    /**
     * 
     * @type {string}
     * @memberof ProductTypeDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductTypeDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductTypeDto
     */
    'code'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductTypeDto
     */
    'order'?: number;
}

