/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductCategoryDto } from './product-category-dto';

/**
 * 
 * @export
 * @interface QuoteProductDto
 */
export interface QuoteProductDto {
    /**
     * 
     * @type {string}
     * @memberof QuoteProductDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteProductDto
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteProductDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteProductDto
     */
    'productCategoryId'?: string;
    /**
     * 
     * @type {ProductCategoryDto}
     * @memberof QuoteProductDto
     */
    'productCategory'?: ProductCategoryDto;
}

