/* tslint:disable */
/* eslint-disable */
/**
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@codewithmukesh.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BaseFilterAdvancedFilter } from './base-filter-advanced-filter';
// May contain unused imports in some cases
// @ts-ignore
import { BaseFilterAdvancedSearch } from './base-filter-advanced-search';
// May contain unused imports in some cases
// @ts-ignore
import { PaginationFilter } from './pagination-filter';
// May contain unused imports in some cases
// @ts-ignore
import { SearchTourSchedulesRequestAllOf } from './search-tour-schedules-request-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleDtoAllOfStatus } from './tour-schedule-dto-all-of-status';

/**
 * @type SearchTourSchedulesRequest
 * @export
 */
export type SearchTourSchedulesRequest = PaginationFilter & SearchTourSchedulesRequestAllOf;


