/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DiscountOnType } from './discount-on-type';
// May contain unused imports in some cases
// @ts-ignore
import { TourDtoStatus } from './tour-dto-status';

/**
 * 
 * @export
 * @interface SearchTourSchedulesForDiscountDto
 */
export interface SearchTourSchedulesForDiscountDto {
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'tourCode'?: string | null;
    /**
     * 
     * @type {TourDtoStatus}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'status'?: TourDtoStatus | null;
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'departureLocationName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'destinationLocationCountryTwoLetterIsoCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'destinationLocationName'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'hasDiscount'?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'departureDate'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'endDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'saleStartDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'saleEndDate'?: Date | null;
    /**
     * 
     * @type {Array<DiscountOnType>}
     * @memberof SearchTourSchedulesForDiscountDto
     */
    'discountOnTypes'?: Array<DiscountOnType>;
}

