/* tslint:disable */
/* eslint-disable */
/**
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@codewithmukesh.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleDtoAllOfStatus } from './tour-schedule-dto-all-of-status';

/**
 * 
 * @export
 * @interface SearchTourSchedulesRequestOfTourScheduleDtoAllOf
 */
export interface SearchTourSchedulesRequestOfTourScheduleDtoAllOf {
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'tourCategoryId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'departureLocationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'destinationLocationId'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'departureDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'endDate'?: Date | null;
    /**
     * 
     * @type {TourScheduleDtoAllOfStatus}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'status'?: TourScheduleDtoAllOfStatus | null;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'fromDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SearchTourSchedulesRequestOfTourScheduleDtoAllOf
     */
    'toDate'?: Date | null;
}

