/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TourInforScheduleSummaryDto
 */
export interface TourInforScheduleSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof TourInforScheduleSummaryDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourInforScheduleSummaryDto
     */
    'tourInforId'?: string;
    /**
     * 
     * @type {number}
     * @memberof TourInforScheduleSummaryDto
     */
    'capacity'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TourInforScheduleSummaryDto
     */
    'remainingCapacity'?: number | null;
}

