/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TourVisaLineStatus } from './tour-visa-line-status';

/**
 * 
 * @export
 * @interface TourVisaLineBase
 */
export interface TourVisaLineBase {
    /**
     * 
     * @type {string}
     * @memberof TourVisaLineBase
     */
    'saleOrderLineTravellerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourVisaLineBase
     */
    'passport'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TourVisaLineBase
     */
    'expiryDate'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TourVisaLineBase
     */
    'note'?: string | null;
    /**
     * 
     * @type {TourVisaLineStatus}
     * @memberof TourVisaLineBase
     */
    'status'?: TourVisaLineStatus;
}



