/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CancellationCondition } from './cancellation-condition';
// May contain unused imports in some cases
// @ts-ignore
import { CommissionCondition } from './commission-condition';
// May contain unused imports in some cases
// @ts-ignore
import { Customer } from './customer';
// May contain unused imports in some cases
// @ts-ignore
import { Employee } from './employee';
// May contain unused imports in some cases
// @ts-ignore
import { PassengerTypeSeat } from './passenger-type-seat';
// May contain unused imports in some cases
// @ts-ignore
import { SaleOrder } from './sale-order';
// May contain unused imports in some cases
// @ts-ignore
import { TourInfor } from './tour-infor';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleAllOfDepositType } from './tour-schedule-all-of-deposit-type';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleAllOfItineraryCode } from './tour-schedule-all-of-itinerary-code';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleAllOfStatus } from './tour-schedule-all-of-status';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleFare } from './tour-schedule-fare';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleMedia } from './tour-schedule-media';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleSurcharge } from './tour-schedule-surcharge';
// May contain unused imports in some cases
// @ts-ignore
import { TourScheduleTourGuide } from './tour-schedule-tour-guide';
// May contain unused imports in some cases
// @ts-ignore
import { TourService } from './tour-service';
// May contain unused imports in some cases
// @ts-ignore
import { Traveller } from './traveller';
// May contain unused imports in some cases
// @ts-ignore
import { Vat } from './vat';
// May contain unused imports in some cases
// @ts-ignore
import { Vendor } from './vendor';

/**
 * 
 * @export
 * @interface TourScheduleAllOf
 */
export interface TourScheduleAllOf {
    /**
     * 
     * @type {Date}
     * @memberof TourScheduleAllOf
     */
    'departureDate'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TourScheduleAllOf
     */
    'endDate'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'tourInforId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'tourScheduleId'?: string | null;
    /**
     * 
     * @type {TourScheduleAllOfStatus}
     * @memberof TourScheduleAllOf
     */
    'status'?: TourScheduleAllOfStatus | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'tourCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'accountingTourCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'groupName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TourScheduleAllOf
     */
    'deposit'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TourScheduleAllOf
     */
    'prepaidDateNo'?: number | null;
    /**
     * 
     * @type {TourScheduleAllOfDepositType}
     * @memberof TourScheduleAllOf
     */
    'depositType'?: TourScheduleAllOfDepositType | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'partnerTourCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'vendorId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'vatId'?: string | null;
    /**
     * 
     * @type {TourScheduleAllOfItineraryCode}
     * @memberof TourScheduleAllOf
     */
    'itineraryCode'?: TourScheduleAllOfItineraryCode | null;
    /**
     * 
     * @type {number}
     * @memberof TourScheduleAllOf
     */
    'nonRefundableVisaFees'?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TourScheduleAllOf
     */
    'saleStartDate'?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TourScheduleAllOf
     */
    'saleEndDate'?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'sellerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourScheduleAllOf
     */
    'travellerId'?: string | null;
    /**
     * 
     * @type {TourInfor}
     * @memberof TourScheduleAllOf
     */
    'tourInfor'?: TourInfor;
    /**
     * 
     * @type {Array<TourScheduleMedia>}
     * @memberof TourScheduleAllOf
     */
    'tourScheduleMedias'?: Array<TourScheduleMedia>;
    /**
     * 
     * @type {Array<TourScheduleFare>}
     * @memberof TourScheduleAllOf
     */
    'tourScheduleFares'?: Array<TourScheduleFare>;
    /**
     * 
     * @type {Array<TourScheduleSurcharge>}
     * @memberof TourScheduleAllOf
     */
    'tourScheduleSurcharges'?: Array<TourScheduleSurcharge>;
    /**
     * 
     * @type {Array<TourScheduleTourGuide>}
     * @memberof TourScheduleAllOf
     */
    'tourScheduleTourGuides'?: Array<TourScheduleTourGuide>;
    /**
     * 
     * @type {Array<PassengerTypeSeat>}
     * @memberof TourScheduleAllOf
     */
    'passengerTypeSeats'?: Array<PassengerTypeSeat>;
    /**
     * 
     * @type {Array<TourService>}
     * @memberof TourScheduleAllOf
     */
    'tourServices'?: Array<TourService>;
    /**
     * 
     * @type {Array<CancellationCondition>}
     * @memberof TourScheduleAllOf
     */
    'cancellationConditions'?: Array<CancellationCondition>;
    /**
     * 
     * @type {Array<CommissionCondition>}
     * @memberof TourScheduleAllOf
     */
    'commissionConditions'?: Array<CommissionCondition>;
    /**
     * 
     * @type {Employee}
     * @memberof TourScheduleAllOf
     */
    'seller'?: Employee;
    /**
     * 
     * @type {Customer}
     * @memberof TourScheduleAllOf
     */
    'customer'?: Customer;
    /**
     * 
     * @type {Vendor}
     * @memberof TourScheduleAllOf
     */
    'vendor'?: Vendor;
    /**
     * 
     * @type {Vat}
     * @memberof TourScheduleAllOf
     */
    'vat'?: Vat;
    /**
     * 
     * @type {Traveller}
     * @memberof TourScheduleAllOf
     */
    'traveller'?: Traveller;
    /**
     * 
     * @type {Array<SaleOrder>}
     * @memberof TourScheduleAllOf
     */
    'saleOrders'?: Array<SaleOrder>;
}

