/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCustomerContactPersonRequest
 */
export interface UpdateCustomerContactPersonRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'customerId': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'contactName': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'position'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'identityID'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'isRepresentative'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCustomerContactPersonRequest
     */
    'deleted'?: boolean | null;
}

