/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { QuoteLineRequest } from './quote-line-request';

/**
 * 
 * @export
 * @interface UpdateQuoteRequest
 */
export interface UpdateQuoteRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateQuoteRequest
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateQuoteRequest
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateQuoteRequest
     */
    'currencyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateQuoteRequest
     */
    'tourScheduleId': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateQuoteRequest
     */
    'note'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateQuoteRequest
     */
    'adtQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateQuoteRequest
     */
    'chdQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateQuoteRequest
     */
    'infQuantity'?: number;
    /**
     * 
     * @type {Array<QuoteLineRequest>}
     * @memberof UpdateQuoteRequest
     */
    'quoteLines'?: Array<QuoteLineRequest>;
    /**
     * 
     * @type {string}
     * @memberof UpdateQuoteRequest
     */
    'tourRoute'?: string | null;
}

