/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateProductRequestImage } from './create-product-request-image';

/**
 * 
 * @export
 * @interface UpdateProductRequest
 */
export interface UpdateProductRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'fullDescription'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    'rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'imagePath'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'brandId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'brandName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'vendorId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'vendorName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'unitId': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'unitName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'currencyId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'currencyName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'productTypeId': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'productTypeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'productGroupId': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'productCategoryId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'productGroupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'inventoryAcct'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'revenueAcct'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'cogsAcct'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProductRequest
     */
    'includedVATInSalePrice'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProductRequest
     */
    'includedVATInPurchasePrice'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProductRequest
     */
    'isActive'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProductRequest
     */
    'deleteCurrentImage'?: boolean;
    /**
     * 
     * @type {CreateProductRequestImage}
     * @memberof UpdateProductRequest
     */
    'image'?: CreateProductRequestImage | null;
}

