/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCancellationTypeRequest
 */
export interface UpdateCancellationTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCancellationTypeRequest
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCancellationTypeRequest
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCancellationTypeRequest
     */
    'isImmediately'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCancellationTypeRequest
     */
    'isBeforeDeparture'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCancellationTypeRequest
     */
    'isAfterAll'?: boolean;
}

