/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI - Tour Operation
 * Clean Architecture Tour Operation for .NET 7 WebApi built with Multitenancy Support.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VendorDto
 */
export interface VendorDto {
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'vendorNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'vendorGroupId'?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'vendorGroupName'?: string;
    /**
     * 
     * @type {number}
     * @memberof VendorDto
     */
    'vendorType'?: number;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'representative'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'vendorInvoiceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'vendorInvoiceName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VendorDto
     */
    'creditLimit'?: number;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'currencyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'currencyName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VendorDto
     */
    'creditTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'customerName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorDto
     */
    'accountNo'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof VendorDto
     */
    'actived'?: boolean;
}

